package frc.robot.modules.swerve;

// Copyright (c) 2026 STZ Robotics
// Open Source Software; you can modify and/or share it under the terms of
// the MIT license file in the root directory of this project.
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;

import com.stzteam.forgemini.io.NetworkIO;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.configuration.KeyManager;
import frc.robot.configuration.constants.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.utils.LimelightHelpers;
import frc.robot.utils.SysIdRoutineManager;
import java.util.Optional;
import java.util.function.Supplier;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain
    implements Subsystem{
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;

  private double GravityFactor = 9.80665;

  private final Field2d field = new Field2d();
  public final String limelightName = "limelight";

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  public final SysIdRoutineManager sysIdManager;

  /* The SysId routine to test */
  private SysIdRoutine m_sysIdRoutineToApply = null;

  private PathConstraints pathConstraints =
      new PathConstraints(4.5, 4.0, Units.degreesToRadians(540), Units.degreesToRadians(720));

  //private final PoseFinder finder;

  private int lastIMUMode = -1;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }

    LimelightHelpers.SetIMUMode(limelightName, 4);
    this.sysIdManager = new SysIdRoutineManager(this);
    this.m_sysIdRoutineToApply = sysIdManager.getSelected();

    configurePathPlanner();
    SmartDashboard.putData("Field", field);

    NetworkIO.set(KeyManager.SWERVE_KEY, "SysID", m_sysIdRoutineToApply.toString());

   // this.finder = new PoseFinder(this, pathConstraints);
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {

    super(drivetrainConstants, odometryUpdateFrequency, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }

    LimelightHelpers.SetIMUMode(limelightName, 4);
    this.sysIdManager = new SysIdRoutineManager(this);
    this.m_sysIdRoutineToApply = sysIdManager.getSelected();

    NetworkIO.set(KeyManager.SWERVE_KEY, "SysID", m_sysIdRoutineToApply.toString());

    configurePathPlanner();

   //this.finder = new PoseFinder(this, pathConstraints);
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta]ᵀ, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta]ᵀ, with units in meters and radians
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }

    LimelightHelpers.SetIMUMode(limelightName, 4);
    this.sysIdManager = new SysIdRoutineManager(this);
    this.m_sysIdRoutineToApply = sysIdManager.getSelected();

    NetworkIO.set(KeyManager.SWERVE_KEY, "SysID", m_sysIdRoutineToApply.toString());

    configurePathPlanner();

    //this.finder = new PoseFinder(this, pathConstraints);
  }

  public void setSysIdRoutine(SysIdRoutine routine) {
    this.m_sysIdRoutineToApply = routine;
  }

  private void configurePathPlanner() {
    try {
      // Cargar configuración de la GUI de PathPlanner (RobotConfig)
      RobotConfig config = RobotConfig.fromGUISettings();

      AutoBuilder.configure(
          () -> this.getState().Pose, // 1. Supplier de Pose
          this::resetPose, // 2. Consumer para resetear pose
          this::getChassisSpeeds, // 3. Supplier de Velocidades actuales
          (speeds, feedforwards) ->
              this.setControl(SwerveRequestFactory.pathPlannerRequest().withSpeeds(speeds)),
          // -----------------------------

          new PPHolonomicDriveController(
              new PIDConstants(5.0, 0.0, 0.0), // PID de Traslación
              new PIDConstants(5.0, 0.0, 0.0) // PID de Rotación
              ),
          config,
          () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
          this);
    } catch (Exception e) {
      DriverStation.reportError("Fallo al configurar PathPlanner: " + e.getMessage(), true);
    }
  }

  public ChassisSpeeds getChassisSpeeds() {
    return getKinematics().toChassisSpeeds(getState().ModuleStates);
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  /**
   * Runs the SysId Quasistatic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Quasistatic test
   * @return Command to run
   */
  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {

    if (m_sysIdRoutineToApply == null) {
      return Commands.none();
    }

    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  /**
   * Runs the SysId Dynamic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Dynamic test
   * @return Command to run
   */
  public Command sysIdDynamic(SysIdRoutine.Direction direction) {

    if (m_sysIdRoutineToApply == null) {
      return Commands.none();
    }

    return m_sysIdRoutineToApply.dynamic(direction);
  }

  @Override
  public void periodic() {
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is disabled.
     * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
     */
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kBlueAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }

    field.setRobotPose(getState().Pose);

    configureLimelightIMU();
    updateLimelightOrientation();
    updateLimeVision();

    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "DriveCurrent_0",
        getModule(0).getDriveMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "DriveCurrent_1",
        getModule(1).getDriveMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "DriveCurrent_2",
        getModule(2).getDriveMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "DriveCurrent_3",
        getModule(3).getDriveMotor().getStatorCurrent().getValueAsDouble());

    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "SteerCurrent_0",
        getModule(0).getSteerMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "SteerCurrent_1",
        getModule(1).getSteerMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "SteerCurrent_2",
        getModule(2).getSteerMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "SteerCurrent_3",
        getModule(3).getSteerMotor().getStatorCurrent().getValueAsDouble());
  }

  private void configureLimelightIMU() {
    int targetMode = DriverStation.isDisabled() ? 1 : 4;

    if (targetMode != lastIMUMode) {
      LimelightHelpers.SetIMUMode(limelightName, targetMode);
      lastIMUMode = targetMode;
      System.out.println("Switched Limelight IMU to Mode: " + targetMode);
    }
  }

  private void updateLimelightOrientation() {
    double robotYaw = getState().Pose.getRotation().getDegrees();
    double robotPitch = getPigeon2().getPitch().getValueAsDouble();
    double robotRoll = getPigeon2().getRoll().getValueAsDouble();

    double robotYawRate = Units.radiansToDegrees(getState().Speeds.omegaRadiansPerSecond);

    LimelightHelpers.SetRobotOrientation_NoFlush(
        limelightName, robotYaw, robotYawRate, robotPitch, 0, robotRoll, 0);

    LimelightHelpers.Flush();
  }

  private void updateLimeVision() {

    LimelightHelpers.PoseEstimate mt2 =
        LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(limelightName);

    if (!LimelightHelpers.getTV(limelightName)) {
      return;
    }

    if (mt2 == null || mt2.tagCount == 0) return;

    if (Math.abs(this.getPigeon2().getAngularVelocityZWorld().getValueAsDouble()) > 85) return;

    if (Math.abs(this.getPigeon2().getAccelerationX().getValueAsDouble() * GravityFactor) >= 2.5
        || Math.abs(this.getPigeon2().getAccelerationY().getValueAsDouble() * GravityFactor) >= 2.5)
      return;

    NetworkIO.set("Chasis", "Mt2", mt2.pose);

    addVisionMeasurement(mt2.pose, mt2.timestampSeconds, VecBuilder.fill(.3, .3, 9999999));
  }

  public double getDistanceToTag() {

    double[] targetPose = LimelightHelpers.getTargetPose_CameraSpace("limelight");

    if (LimelightHelpers.getTV("limelight")) {

      double distanceZ = targetPose[2];

      return distanceZ;
    }

    return 0.0;
  }

  public double calculateDistanceTrig(double targetHeightMeters) {
    double cameraHeightMeters = 0.5; // EJEMPLO: Tu camara está a 50cm del piso
    double cameraMountAngleDegrees = 25.0; // EJEMPLO: Inclinada 25 grados hacia arriba

    double ty = LimelightHelpers.getTY("limelight"); // angulo vertical que ve la cámara

    if (LimelightHelpers.getTV("limelight")) {
      double angleToGoalRadians = Math.toRadians(cameraMountAngleDegrees + ty);

      // Evitar división por cero
      if (angleToGoalRadians == 0) return 0.0;

      return (targetHeightMeters - cameraHeightMeters) / Math.tan(angleToGoalRadians);
    }
    return 0.0;
  }

  public void aproachY() {
    double ty = LimelightHelpers.getTY(KeyManager.LIMELIGHT_KEY);
    double xSpeed = -0.1 * ty;

    setControl(
        SwerveRequestFactory.simpleDriveRequest()
            .withVelocityX(xSpeed)
            .withVelocityY(0)
            .withRotationalRate(0));
  }

  /** MODO 1: AUTO-DOCK (El robot hace todo) Se acerca al tag y se alinea usando RobotCentric. */
  public void aproachXY() {
    double ty = LimelightHelpers.getTY(KeyManager.LIMELIGHT_KEY);
    double tx = LimelightHelpers.getTX(KeyManager.LIMELIGHT_KEY);

    double xSpeed = -0.1 * ty;
    double ySpeed = -0.05 * tx;

    setControl(
        SwerveRequestFactory.simpleDriveRequest()
            .withVelocityX(xSpeed)
            .withVelocityY(0)
            .withRotationalRate(ySpeed));
  }

  /**
   * MODO 2: AIM ASSIST (Para Teleop) El piloto controla X/Y, el robot controla el giro hacia el
   * tag.
   *
   * @param xSpeed Velocidad X del Joystick
   * @param ySpeed Velocidad Y del Joystick
   */
  public void driveFacingTag(double xSpeed, double ySpeed) {
    double tx = LimelightHelpers.getTX("limelight");
    boolean hasTarget = LimelightHelpers.getTV("limelight");

    // Calcular el angulo actual del robot
    Rotation2d currentHeading = this.getPigeon2().getRotation2d();

    // Si vemos tag, el angulo deseado es: (MiAngulo - ErrorDelTag)
    // Si no vemos tag, mantenemos el angulo actual
    Rotation2d targetHeading =
        hasTarget ? currentHeading.minus(Rotation2d.fromDegrees(tx)) : currentHeading;

    // Usamos el request de Aim de la Factory
    setControl(
        SwerveRequestFactory.aimRequest()
            .withVelocityX(xSpeed)
            .withVelocityY(ySpeed)
            .withTargetDirection(targetHeading));
  }

  public void moveX(double speed) {
    setControl(SwerveRequestFactory.simpleDriveRequest().withVelocityX(speed));
  }

  public void moveY(double speed) {
    setControl(SwerveRequestFactory.simpleDriveRequest().withVelocityY(speed));
  }

  // public PoseFinder getPoseFinder() {
  //   return finder;
  // }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - m_lastSimTime;
              m_lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   */
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * <p>Note that the vision measurement standard deviations passed into this method will continue
   * to apply to future measurements until a subsequent call to {@link
   * #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the form
   *     [x, y, theta]ᵀ, with units in meters and radians.
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters,
      double timestampSeconds,
      Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(
        visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
  }

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds.
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }

  public Subsystem asSubsystem() {
    return this;
  }
}