package frc.robot.modules.swerve;

// Copyright (c) 2026 STZ Robotics
// Open Source Software; you can modify and/or share it under the terms of
// the MIT license file in the root directory of this project.
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;
import com.pathplanner.lib.util.DriveFeedforwards;
import com.pathplanner.lib.util.PathPlannerLogging;

import com.stzteam.forgemini.io.NetworkIO;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.configuration.KeyManager;
import frc.robot.configuration.constants.Constants;
import frc.robot.configuration.constants.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.configuration.constants.moduleconstants.SwerveConstants;
import frc.robot.utils.LimelightHelpers;
import frc.robot.utils.SysIdRoutineManager;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.function.Supplier;


/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain
  implements Subsystem{
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private MarsSimGlue m_marsGlue = null;

  private double GravityFactor = 9.80665;

  // ---- Filtros de vision (puntos de partida; ajustar con los logs de VisionAccepted) ----
  /** Limelight recomienda rechazar MegaTag2 por encima de ~720 deg/s. */
  private static final double kMaxYawRateDegPerSec = 720.0;
  /** Aceleracion plana maxima (m/s^2) para aceptar una medicion (choques / golpes). */
  private static final double kMaxAccelMps2 = 6.0;
  /** Mas lejos que esto el ruido de la camara es demasiado alto para corregir la pose. */
  private static final double kMaxTagDistMeters = 5.0;
  /** Desviacion estandar XY = base + k * distancia^2 / numero_de_tags (metros). */
  private static final double kVisionBaseStd = 0.1;
  private static final double kVisionDistStd = 0.05;

  private final Field2d field = new Field2d();
  public final String limelightName = "limelight";

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  public final SysIdRoutineManager sysIdManager;

  /* The SysId routine to test */
  private SysIdRoutine m_sysIdRoutineToApply = null;

  private PathConstraints pathConstraints =
      new PathConstraints(4.5, 4.0, Units.degreesToRadians(540), Units.degreesToRadians(720));

  //private final PoseFinder finder;

  private final SwerveRequest.ApplyRobotSpeeds pathPlannerRequest =
      SwerveRequestFactory.pathPlannerRequest();
  private RobotConfig robotConfig = null;
  private Pose2d lastPathTargetPose = null;
  private Consumer<Pose2d> pathTargetListener = null;

  private int lastIMUMode = -1;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }

    LimelightHelpers.SetIMUMode(limelightName, 4);
    this.sysIdManager = new SysIdRoutineManager(this);
    this.m_sysIdRoutineToApply = sysIdManager.getSelected();

    configurePathPlanner();
    SmartDashboard.putData("Field", field);

    NetworkIO.set(KeyManager.SWERVE_KEY, "SysID", m_sysIdRoutineToApply.toString());

    //this.finder = new PoseFinder(this, pathConstraints);
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {

    super(drivetrainConstants, odometryUpdateFrequency, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }

    LimelightHelpers.SetIMUMode(limelightName, 4);
    this.sysIdManager = new SysIdRoutineManager(this);
    this.m_sysIdRoutineToApply = sysIdManager.getSelected();

    NetworkIO.set(KeyManager.SWERVE_KEY, "SysID", m_sysIdRoutineToApply.toString());

    configurePathPlanner();

    //this.finder = new PoseFinder(this, pathConstraints);
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta]ᵀ, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta]ᵀ, with units in meters and radians
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }

    LimelightHelpers.SetIMUMode(limelightName, 4);
    this.sysIdManager = new SysIdRoutineManager(this);
    this.m_sysIdRoutineToApply = sysIdManager.getSelected();

    NetworkIO.set(KeyManager.SWERVE_KEY, "SysID", m_sysIdRoutineToApply.toString());

    configurePathPlanner();

    //this.finder = new PoseFinder(this, pathConstraints);
  }

  public void setSysIdRoutine(SysIdRoutine routine) {
    this.m_sysIdRoutineToApply = routine;
  }

  private void configurePathPlanner() {
    try {
      // Cargar configuración de la GUI de PathPlanner (RobotConfig)
      robotConfig = RobotConfig.fromGUISettings();

      AutoBuilder.configure(
          () -> this.getState().Pose, // 1. Supplier de Pose
          this::resetPose, // 2. Consumer para resetear pose
          this::getChassisSpeeds, // 3. Supplier de Velocidades actuales
          this::applyPathPlannerOutput, // 4. Velocidades + feedforwards de fuerza por rueda
          new PPHolonomicDriveController(
              SwerveConstants.PathTranslationPID, // PID de Traslación
              SwerveConstants.PathRotationPID // PID de Rotación
              ),
          robotConfig,
          () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
          this);
    } catch (Exception e) {
      DriverStation.reportError("Fallo al configurar PathPlanner: " + e.getMessage(), true);
    }

    // Pose objetivo vs pose real del path activo, para ver el error de seguimiento en AdvantageScope
    PathPlannerLogging.setLogTargetPoseCallback(
        pose -> {
          lastPathTargetPose = pose;
          field.getObject("PathTarget").setPose(pose);
          NetworkIO.set(KeyManager.SWERVE_KEY, "PathTargetPose", pose);
          if (pathTargetListener != null) {
            pathTargetListener.accept(pose);
          }
        });
    PathPlannerLogging.setLogActivePathCallback(
        poses -> field.getObject("ActivePath").setPoses(poses));
  }

  /** Manda a los modulos la salida de PathPlanner, incluyendo el feedforward de fuerza por rueda. */
  public void applyPathPlannerOutput(ChassisSpeeds speeds, DriveFeedforwards feedforwards) {
    setControl(
        pathPlannerRequest
            .withSpeeds(speeds)
            .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
            .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons()));
  }

  /** RobotConfig cargado de deploy/pathplanner/settings.json, o null si no se pudo cargar. */
  public RobotConfig getRobotConfig() {
    return robotConfig;
  }

  public Pose2d getLastPathTargetPose() {
    return lastPathTargetPose;
  }

  /** Recibe cada pose objetivo que publica PathPlanner mientras sigue un path (null para quitarlo). */
  public void setPathTargetListener(Consumer<Pose2d> listener) {
    this.pathTargetListener = listener;
  }

  public ChassisSpeeds getChassisSpeeds() {
    return getKinematics().toChassisSpeeds(getState().ModuleStates);
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  /**
   * Runs the SysId Quasistatic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Quasistatic test
   * @return Command to run
   */
  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {

    if (m_sysIdRoutineToApply == null) {
      return Commands.none();
    }

    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  /**
   * Runs the SysId Dynamic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Dynamic test
   * @return Command to run
   */
  public Command sysIdDynamic(SysIdRoutine.Direction direction) {

    if (m_sysIdRoutineToApply == null) {
      return Commands.none();
    }

    return m_sysIdRoutineToApply.dynamic(direction);
  }

  @Override
  public void periodic() {
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is disabled.
     * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
     */
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kBlueAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }

    field.setRobotPose(getState().Pose);

    configureLimelightIMU();
    updateLimelightOrientation();
    updateLimeVision();

    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "DriveCurrent_0",
        getModule(0).getDriveMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "DriveCurrent_1",
        getModule(1).getDriveMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "DriveCurrent_2",
        getModule(2).getDriveMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "DriveCurrent_3",
        getModule(3).getDriveMotor().getStatorCurrent().getValueAsDouble());

    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "SteerCurrent_0",
        getModule(0).getSteerMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "SteerCurrent_1",
        getModule(1).getSteerMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "SteerCurrent_2",
        getModule(2).getSteerMotor().getStatorCurrent().getValueAsDouble());
    NetworkIO.set(
        KeyManager.SWERVE_KEY,
        "SteerCurrent_3",
        getModule(3).getSteerMotor().getStatorCurrent().getValueAsDouble());
  }

  private void configureLimelightIMU() {
    int targetMode = DriverStation.isDisabled() ? 1 : 4;

    if (targetMode != lastIMUMode) {
      LimelightHelpers.SetIMUMode(limelightName, targetMode);
      lastIMUMode = targetMode;
      System.out.println("Switched Limelight IMU to Mode: " + targetMode);
    }
  }

  private void updateLimelightOrientation() {
    double robotYaw = getState().Pose.getRotation().getDegrees();
    double robotPitch = getPigeon2().getPitch().getValueAsDouble();
    double robotRoll = getPigeon2().getRoll().getValueAsDouble();

    double robotYawRate = Units.radiansToDegrees(getState().Speeds.omegaRadiansPerSecond);

    LimelightHelpers.SetRobotOrientation_NoFlush(
        limelightName, robotYaw, robotYawRate, robotPitch, 0, robotRoll, 0);

    LimelightHelpers.Flush();
  }

  private void updateLimeVision() {

    boolean accepted = false;
    try {
      if (!LimelightHelpers.getTV(limelightName)) return;

      LimelightHelpers.PoseEstimate mt2 =
          LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(limelightName);

      if (mt2 == null || mt2.tagCount == 0) return;
      if (mt2.avgTagDist > kMaxTagDistMeters) return;

      if (Math.abs(this.getPigeon2().getAngularVelocityZWorld().getValueAsDouble())
          > kMaxYawRateDegPerSec) return;

      double ax = this.getPigeon2().getAccelerationX().getValueAsDouble() * GravityFactor;
      double ay = this.getPigeon2().getAccelerationY().getValueAsDouble() * GravityFactor;
      if (Math.hypot(ax, ay) > kMaxAccelMps2) return;

      // Pose basura: (0,0) exacto, NaN o fuera de la cancha.
      Translation2d p = mt2.pose.getTranslation();
      if (Double.isNaN(p.getX()) || Double.isNaN(p.getY())) return;
      if (p.getNorm() < 1e-6) return;
      if (p.getX() < 0 || p.getX() > Constants.FIELD_LENGTH_METERS) return;
      if (p.getY() < 0 || p.getY() > Constants.FIELD_WIDTH_METERS) return;

      double xyStd =
          kVisionBaseStd + kVisionDistStd * mt2.avgTagDist * mt2.avgTagDist / mt2.tagCount;

      NetworkIO.set("Chasis", "Mt2", mt2.pose);
      NetworkIO.set("Chasis", "VisionTagDist", mt2.avgTagDist);
      NetworkIO.set("Chasis", "VisionStdDev", xyStd);

      // Theta enorme: el heading lo manda el Pigeon, la vision solo corrige X/Y.
      addVisionMeasurement(mt2.pose, mt2.timestampSeconds, VecBuilder.fill(xyStd, xyStd, 9999999));
      accepted = true;
    } finally {
      NetworkIO.set("Chasis", "VisionAccepted", accepted);
    }
  }

  /**
   * Distancia (m) desde la salida del shooter hasta el centro del hub, calculada con la pose
   * fusionada (odometria + vision). No depende de ver un tag en este instante.
   */
  public double getDistanceToHub() {
    boolean red = DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red;
    Translation2d hub =
        red
            ? new Translation2d(
                Constants.FIELD_LENGTH_METERS - Constants.HUB_BLUE.getX(),
                Constants.FIELD_WIDTH_METERS - Constants.HUB_BLUE.getY())
            : Constants.HUB_BLUE;

    Translation2d shooter =
        getState()
            .Pose
            .transformBy(new Transform2d(Constants.ROBOT_TO_SHOOTER, Rotation2d.kZero))
            .getTranslation();

    return shooter.getDistance(hub);
  }

  public double getDistanceToTag() {

    double[] targetPose = LimelightHelpers.getTargetPose_CameraSpace("limelight");

    if (LimelightHelpers.getTV("limelight")) {

      double distanceZ = targetPose[2];

      return distanceZ;
    }

    return 0.0;
  }

  public double calculateDistanceTrig(double targetHeightMeters) {
    double cameraHeightMeters = 0.5; // EJEMPLO: Tu camara está a 50cm del piso
    double cameraMountAngleDegrees = 25.0; // EJEMPLO: Inclinada 25 grados hacia arriba

    double ty = LimelightHelpers.getTY("limelight"); // angulo vertical que ve la cámara

    if (LimelightHelpers.getTV("limelight")) {
      double angleToGoalRadians = Math.toRadians(cameraMountAngleDegrees + ty);

      // Evitar división por cero
      if (angleToGoalRadians == 0) return 0.0;

      return (targetHeightMeters - cameraHeightMeters) / Math.tan(angleToGoalRadians);
    }
    return 0.0;
  }

  public void aproachY() {
    double ty = LimelightHelpers.getTY(KeyManager.LIMELIGHT_KEY);
    double xSpeed = -0.1 * ty;

    setControl(
        SwerveRequestFactory.simpleDriveRequest()
            .withVelocityX(xSpeed)
            .withVelocityY(0)
            .withRotationalRate(0));
  }

  /** MODO 1: AUTO-DOCK (El robot hace todo) Se acerca al tag y se alinea usando RobotCentric. */
  public void aproachXY() {
    double ty = LimelightHelpers.getTY(KeyManager.LIMELIGHT_KEY);
    double tx = LimelightHelpers.getTX(KeyManager.LIMELIGHT_KEY);

    double xSpeed = -0.1 * ty;
    double ySpeed = -0.05 * tx;

    setControl(
        SwerveRequestFactory.simpleDriveRequest()
            .withVelocityX(xSpeed)
            .withVelocityY(0)
            .withRotationalRate(ySpeed));
  }

  /**
   * MODO 2: AIM ASSIST (Para Teleop) El piloto controla X/Y, el robot controla el giro hacia el
   * tag.
   *
   * @param xSpeed Velocidad X del Joystick
   * @param ySpeed Velocidad Y del Joystick
   */
  public void driveFacingTag(double xSpeed, double ySpeed) {
    double tx = LimelightHelpers.getTX("limelight");
    boolean hasTarget = LimelightHelpers.getTV("limelight");

    // Calcular el angulo actual del robot
    Rotation2d currentHeading = this.getPigeon2().getRotation2d();

    // Si vemos tag, el angulo deseado es: (MiAngulo - ErrorDelTag)
    // Si no vemos tag, mantenemos el angulo actual
    Rotation2d targetHeading =
        hasTarget ? currentHeading.minus(Rotation2d.fromDegrees(tx)) : currentHeading;

    // Usamos el request de Aim de la Factory
    setControl(
        SwerveRequestFactory.aimRequest()
            .withVelocityX(xSpeed)
            .withVelocityY(ySpeed)
            .withTargetDirection(targetHeading));
  }

  public void moveX(double speed) {
    setControl(SwerveRequestFactory.simpleDriveRequest().withVelocityX(speed));
  }

  public void moveY(double speed) {
    setControl(SwerveRequestFactory.simpleDriveRequest().withVelocityY(speed));
  }
/* 
  public PoseFinder getPoseFinder() {
    return finder;
  }
*/
  private void startSimThread() {
    // Con MARS Simulation Studio corriendo, la fisica sale de Gazebo (masa, patinaje, choques);
    // sin el, el glue llama a updateSimState y queda la simulacion cinematica de CTRE de siempre.
    m_marsGlue = new MarsSimGlue(this);

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier = new Notifier(m_marsGlue::update);
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   */
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * <p>Note that the vision measurement standard deviations passed into this method will continue
   * to apply to future measurements until a subsequent call to {@link
   * #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the form
   *     [x, y, theta]ᵀ, with units in meters and radians.
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters,
      double timestampSeconds,
      Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(
        visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
  }

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds.
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }

}